spring:
#  zipkin:              #不集成kafka配置方式   通过http追踪
#    baseUrl:  localhost:9411
  sleuth:
        web:
          client:
            enabled: true
        sampler:
          percentage: 1
  cloud:              #kafka集成方式   数据先存储在kafka中然后zipkin从kafka中读取追踪数据
      stream:
         kafka:
           binder:
             brokers: 127.0.0.1
             defaultBrokerPort: 9092
             zkNodes: 127.0.0.1
             defaultZkPort: 2181
             minPartitionCount: 1
             autoCreateTopics: true
             autoAddPartitions: true
  datasource:
    platform: mysql
    url: jdbc:mysql://101.132.74.104:3306/oauth2
    username: root
    password: 'ABC456lxl:'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 101.132.74.104
    port: 6379
    password: 123456

security:
  oauth2:
    resource:
      filter-order: 3


eureka:
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}
  client:
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true

signing.key: "345345fsdfsf5345"

